{% set name = "premise" %}
{% set version = environ.get('VERSION', "0.0.0") %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  path: ..

build:
  noarch: python
  number: 0

outputs:
  - name: {{ name }}
    requirements:
      host:
        - python
        - setuptools
      run:
        - python
        - bottleneck
        - bw2data
        - bw2io
        - ecoinvent_interface
        - constructive_geometries>=0.9.5
        - cryptography
        - datapackage
        - numpy <2.0.0
        - pandas
        - platformdirs
        - prettytable
        - pyarrow
        - pycountry
        - pyYaml
        - requests
        - schema
        - sparse>=0.14.0
        - wurst>=0.4
        - xarray<=2024.2.0
        - tqdm
        - unfold

  - name: {{ name }}-bw25
    requirements:
      host:
        - python
        - setuptools
      run:
        - python
        - bottleneck
        - bw2calc >=2.0.1
        - bw2data >=4.0.3
        - bw2io >=0.9.4
        - ecoinvent_interface
        - constructive_geometries>=0.9.5
        - cryptography
        - datapackage
        - numpy <2.0.0
        - pandas
        - platformdirs
        - prettytable
        - pyarrow
        - pycountry
        - pyYaml
        - requests
        - schema
        - sparse>=0.14.0
        - wurst>=0.4
        - xarray<=2024.2.0
        - tqdm
        - unfold

  - name: {{ name }}-bw2
    requirements:
      host:
        - python
        - setuptools
      run:
        - python
        - bottleneck
        - bw2calc ==1.8.2
        - bw2data ==3.6.6
        - bw2io ==0.8.12
        - ecoinvent_interface
        - constructive_geometries>=0.9.5
        - cryptography
        - datapackage
        - numpy <2.0.0
        - pandas
        - platformdirs
        - prettytable
        - pyarrow
        - pycountry
        - pyYaml
        - requests
        - schema
        - sparse>=0.14.0
        - wurst>=0.4
        - xarray<=2024.2.0
        - tqdm
        - unfold

test:
  imports:
    - premise

about:
  home: https://github.com/polca/premise
  license: BSD License
  summary: 'Coupling Integrated Assessment Models and Life Cycle Assessment.'
license_family: BSD
license_file: LICENSE